### PR TITLE
Support alternate form of .using()

### PR DESCRIPTION
**Pull request by tdeck**
This allows you to write .using() clauses that build the message dynamically at validation time. If .using()'s last argument is a function, the return value will either be a message (the error) or null/undefined (no error; valid).

### CODE REVIEW

**Comment by tdeck** [comment]
Bump!

**Comment by eventualbuddha** [comment]
Sorry for the delay on this. As in our private conversation, I think there should be a more explicit way to do this than simply not providing a message and using whatever the return value of the predicate is. What do you think of this API?

```js
.using(name => {
  if (name === 'Bob') {
    return true;
  } else {
    return LGTM.result(false, `Your name is ${name}, but it should be "Bob".`);
  }
})
```

**Comment by kitak** [comment]
:+1:

**Comment by eventualbuddha** [comment]
Closing for inactivity.

**Pull request closed without merging**
